# Generated by Django 4.0.3 on 2022-04-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('sales', models.IntegerField()),
                ('GM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gm')),
            ],
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('sales', models.IntegerField()),
                ('AGM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agm')),
            ],
        ),
        migrations.AddField(
            model_name='agm',
            name='RGM_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rgm'),
        ),
    ]
